#ifndef RT_RAYTRACER_GLOBALS_HPP
#define RT_RAYTRACER_GLOBALS_HPP

#if defined MAKE_RAYTRACER_LIBRARY
    #define RAYTRACER_LIB_EXPORT Q_DECL_EXPORT
#else
    #define RAYTRACER_LIB_EXPORT Q_DECL_IMPORT
#endif

#endif